function params = defaultGenerationParams()

params = struct( ...
    "XMin", -100, ...
    "XMax", 100, ...
    "YMin", -100, ...
    "YMax", 100, ...
    "RegionCount", 10, ...
    "RadiusMin", 10, ...
    "RadiusMax", 30, ...
    "ThreatResolution", 0.1);

end
