function lineHandle = drawMap(ax, mapState, pathPoints, renderOptions)

if nargin < 3
    pathPoints = [];
end
if nargin < 4
    renderOptions = struct();
end

% Compose the base heatmap first, then overlay the current path.
displayMap(ax, ...
    mapState.Matrix, ...
    mapState.XMin, ...
    mapState.XMax, ...
    mapState.YMin, ...
    mapState.YMax, ...
    mapState.Threats, ...
    renderOptions);

lineHandle = drawPath(ax, pathPoints);
title(ax, "Map: " + formatMapDisplayName(mapState));

end
