function drawMap(ax, mapState, pathPoints)

if nargin < 3
    pathPoints = [];
end

% Compose the base heatmap first, then overlay the current path.
displayMap(ax, ...
    mapState.Matrix, ...
    mapState.XMin, ...
    mapState.XMax, ...
    mapState.YMin, ...
    mapState.YMax, ...
    mapState.Threats);

drawPath(ax, pathPoints);
title(ax, "Map: " + formatMapDisplayName(mapState));

end
