function mapState = loadMap(filename)

filename = char(string(filename));
[mapMatrix, xmin, xmax, ymin, ymax] = readMap(filename);
mapJson = jsondecode(fileread(filename));
[folder, name, ~] = fileparts(filename);

if isfield(mapJson, "Threats")
    threats = mapJson.Threats;
else
    threats = struct([]);
end

mapState = struct( ...
    "Matrix", mapMatrix, ...
    "XMin", xmin, ...
    "XMax", xmax, ...
    "YMin", ymin, ...
    "YMax", ymax, ...
    "Threats", threats, ...
    "Folder", string(folder), ...
    "JsonFile", string(filename), ...
    "Name", string(name));

end
